### ISSUE TITLE
Submitting emails files through API.

### ISSUE THREAD

**Issue by sbnajardhane** [jeshan/lambdatv#1]
Here, you have used the Amazon CLI console to submit the request for sending those emails.
`aws ses send-bulk-templated-email --cli-input-json file://example-email.json`

Is there any way I can submit this request from my Python code.
I will create a emails JSON file then upload it to S3 and then using some API to submit that S3 file to SES for sending those emails

**Comment by jeshan** [comment]
The cli is based on the same code as the python sdk, so yes you should be able to do the same from python. The method you're looking for is `send_raw_email`:

```python
import boto3
client = boto3.client('ses')
client.send_raw_email(...)
```

See the boto3 docs for details:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ses.html#SES.Client.send_raw_email

Also, check the python snippet at aws docs:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html#send-email-raw-api
There's an example that you can copy paste.
